### ISSUE TITLE
clang error

### ISSUE THREAD

**Issue by jtc25** [barnex/fftw#1]
when I "go get github.com.barnex/fftw" I get clang: error: unknown argument: '-malign-double' What is the problem?

Thanks for any help
Jim

**Comment by barnex** [comment]
Have you tried using gcc instead of llvm?

**Comment by jtc25** [comment]
I deleted all the references to -malign-double & -malign-float. Now it compiles with some warnings and seems to produce the correct results. In some files there was include malloc.h" statement which I deleted. If you want a detailed explanation I'm willing to provide it.
