### ISSUE TITLE
Compiling on windows

### ISSUE THREAD

**Issue by marcopeereboom** [barnex/fftw#2]
I can't get this to link on windows.

I used mingw64 and the standard 'go get -x github.com/barnex/fftw' command.  Compiling seems to go ok but once it gets to the linking stage the full path of all the .o seems to trip up windows MAXPATH.

Last line printed:
go build github.com/barnex/fftw/internal/float: gcc: fork/exec C:\Program Files\mingw-w64\x86_64-6.2.0-posix-seh-rt_v5-rev1\mingw64\bin\gcc.exe: The filename or extension is too long.

Got any clues for me?

**Comment by barnex** [comment]
I'm afraid windows indeed can't handle the large number of files. I know 
no way around that :-(

**Comment by marcopeereboom** [comment]
Oh windows, you make me so sad...
